export const navItems = [
  { slug: 'policies', title: 'Policy Management', icon: '📋', badge: 'core', api: '/policies' },
  { slug: 'customers', title: 'Customer Management', icon: '👥', badge: 'core', api: '/customers' },
  { slug: 'claims', title: 'Claims Processing', icon: '📑', badge: 'ai', api: '/claims' },
  { slug: 'risk-assessment', title: 'Risk Assessment', icon: '🎯', badge: 'ai', api: '/risk-assessment' },
  { slug: 'underwriting-rules', title: 'Underwriting Rules', icon: '⚙️', badge: 'ai', api: '/underwriting-rules' },
  { slug: 'fraud-detection', title: 'Fraud Detection', icon: '🔍', badge: 'ai', api: '/fraud-detection' },
  { slug: 'premium-calculator', title: 'Premium Calculator', icon: '💰', badge: 'ai', api: '/premium-calculator' },
  { slug: 'documents', title: 'Document Analysis', icon: '📄', badge: 'ai', api: '/documents' },
  { slug: 'compliance', title: 'Compliance Monitoring', icon: '✅', badge: 'core', api: '/compliance' },
  { slug: 'reinsurance', title: 'Reinsurance Treaties', icon: '🤝', badge: 'core', api: '/reinsurance' },
  { slug: 'loss-ratio', title: 'Loss Ratio Analysis', icon: '📊', badge: 'ai', api: '/loss-ratio' },
  { slug: 'agents-brokers', title: 'Agents & Brokers', icon: '🏢', badge: 'core', api: '/agents-brokers' },
  { slug: 'audit-log', title: 'Audit Trail', icon: '📝', badge: 'analytics', api: '/audit-log' },
  { slug: 'reports', title: 'Reports & Analytics', icon: '📈', badge: 'analytics', api: '/reports' },
  { slug: 'renewals', title: 'Policy Renewals', icon: '🔄', badge: 'ai', api: '/renewals' },
  { slug: 'quote-bind-issue', title: 'Quote Bind Issue', icon: 'QBI', badge: 'core', api: '/quote-bind-issue' },
  { slug: 'billing-payments', title: 'Billing & Payments', icon: 'PAY', badge: 'core', api: '/billing-payments' },
  { slug: 'endorsements', title: 'Endorsements', icon: 'END', badge: 'core', api: '/endorsements' },
  { slug: 'cancellations', title: 'Cancellations', icon: 'CAN', badge: 'core', api: '/cancellations' },
  { slug: 'esignature-packets', title: 'E-Signature', icon: 'SIG', badge: 'core', api: '/esignature-packets' },
  { slug: 'rbac-admin', title: 'RBAC Admin', icon: 'RBAC', badge: 'core', api: '/rbac-admin' },
  { slug: 'audit-exports', title: 'Audit Exports', icon: 'EXP', badge: 'analytics', api: '/audit-exports' },
  { slug: '__policy-recommendation', title: 'Policy Recommendation', icon: '✨', badge: 'ai', route: '/policy-recommendation' },
  { slug: '__ai-center', title: 'AI Center', icon: '🧠', badge: 'ai', route: '/ai-center' },
  { slug: '__custom-views', title: 'UW Views', icon: '🗂️', badge: 'analytics', route: '/custom-views' },
  { slug: '__customer-portal', title: 'Customer Portal', icon: '👤', badge: 'core', route: '/customer-portal' },
  { slug: '__agent-portal', title: 'Agent Portal', icon: '🏢', badge: 'core', route: '/agent-portal' },
  { slug: '__uw-workflow', title: 'UW Workflow', icon: '↗', badge: 'core', route: '/uw-workflow' },
  { slug: '__integration-center', title: 'Integration Center', icon: '⇄', badge: 'core', route: '/integration-center' },
  { slug: '__agentic-underwriting', title: 'Agentic Underwriting', icon: 'AI', badge: 'ai', route: '/agentic-underwriting' },
  { slug: '__renewal-optimizer', title: 'Renewal Optimizer', icon: 'RO', badge: 'ai', route: '/renewal-optimizer' },
  { slug: '__appetite-drift', title: 'Appetite Drift', icon: 'AD', badge: 'analytics', route: '/appetite-drift-monitor' },
  { slug: '__production-controls', title: 'Production Controls', icon: '🛡️', badge: 'core', route: '/production-controls' },
];
